services:
  postgres:
    image: postgres
    container_name: weather_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  redis:
    image: redis
    container_name: weather_cache
    ports:
      - 6379:6379

  server:
    build: .
    container_name: weather_server
    env_file:
      - .env.docker
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
